vich_uploader:
    db_driver: orm

    mappings:
       artistes:
           uri_prefix: /images/artists
           upload_destination: '%kernel.project_dir%/public/uploads/artists/pictures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
